UPDATE Leaders
SET
  Description = 'TXT_KEY_LEADER_ROBOT3_DESC'
WHERE Type = 'LEADER_ARC';



UPDATE Leaders
SET
  ArtDefineTag = 'Robot1_Scene.xml',
  Description = 'TXT_KEY_LEADER_ROBOT1_DESC',
  IconAtlas = 'ROBOT1_LEADER_ATLAS',
  PortraitIndex = 0
WHERE Type = 'LEADER_CHUNGSU';



UPDATE Leaders
SET
  Description = 'TXT_KEY_LEADER_ALIEN3_DESC'
WHERE Type = 'LEADER_FRANCO_IBERIA';



UPDATE Leaders
SET
  Description = 'TXT_KEY_LEADER_ROBOT2_DESC'
WHERE Type = 'LEADER_INTEGR';



UPDATE Leaders
SET
  ArtDefineTag = 'Alien1_Scene.xml',
  Description = 'TXT_KEY_LEADER_ALIEN1_DESC',
  IconAtlas = 'ALIEN1_LEADER_ATLAS',
  PortraitIndex = 0
WHERE Type = 'LEADER_POLYSTRALIA';



UPDATE Leaders
SET
  Description = 'TXT_KEY_LEADER_ALIEN2_DESC'
WHERE Type = 'LEADER_RUSSIA';




DELETE FROM Leader_Flavors
WHERE LeaderType != 'LEADER_ALIEN'
  AND FlavorType IN (
    'FLAVOR_EMANCIPATION',
    'FLAVOR_HARMONY',
    'FLAVOR_PROMISED_LAND',
    'FLAVOR_PURITY',
    'FLAVOR_SUPREMACY',
    'FLAVOR_TRANSCENDENCE'
  );

INSERT INTO Leader_Flavors (LeaderType, FlavorType, Flavor)
SELECT
  leaders.LeaderType,
  flavours.FlavorType,
  flavours.Flavor
FROM (
  SELECT 'LEADER_ARC' AS LeaderType UNION ALL
  SELECT 'LEADER_CHUNGSU' AS LeaderType UNION ALL
  SELECT 'LEADER_INTEGR' AS LeaderType
) AS leaders
CROSS JOIN (
  SELECT 'FLAVOR_EMANCIPATION' AS FlavorType, 9 AS Flavor UNION ALL
  SELECT 'FLAVOR_HARMONY' AS FlavorType, -2 AS Flavor UNION ALL
  SELECT 'FLAVOR_PROMISED_LAND' AS FlavorType, -2 AS Flavor UNION ALL
  SELECT 'FLAVOR_PURITY' AS FlavorType, -2 AS Flavor UNION ALL
  SELECT 'FLAVOR_SUPREMACY' AS FlavorType, 12 AS Flavor UNION ALL
  SELECT 'FLAVOR_TRANSCENDENCE' AS FlavorType, -2 AS Flavor
) AS flavours;

INSERT INTO Leader_Flavors (LeaderType, FlavorType, Flavor)
SELECT
  leaders.LeaderType,
  flavours.FlavorType,
  flavours.Flavor
FROM (
  SELECT 'LEADER_FRANCO_IBERIA' AS LeaderType UNION ALL
  SELECT 'LEADER_POLYSTRALIA' AS LeaderType UNION ALL
  SELECT 'LEADER_RUSSIA' AS LeaderType
) AS leaders
CROSS JOIN (
  SELECT 'FLAVOR_EMANCIPATION' AS FlavorType, -2 AS Flavor UNION ALL
  SELECT 'FLAVOR_HARMONY' AS FlavorType, 12 AS Flavor UNION ALL
  SELECT 'FLAVOR_PROMISED_LAND' AS FlavorType, -2 AS Flavor UNION ALL
  SELECT 'FLAVOR_PURITY' AS FlavorType, -2 AS Flavor UNION ALL
  SELECT 'FLAVOR_SUPREMACY' AS FlavorType, -2 AS Flavor UNION ALL
  SELECT 'FLAVOR_TRANSCENDENCE' AS FlavorType, 9 AS Flavor
) AS flavours;

INSERT INTO Leader_Flavors (LeaderType, FlavorType, Flavor)
SELECT
  leaders.LeaderType,
  flavours.FlavorType,
  flavours.Flavor
FROM (
  SELECT 'LEADER_AFRICAN_UNION' AS LeaderType UNION ALL
  SELECT 'LEADER_AL_FALAH' AS LeaderType UNION ALL
  SELECT 'LEADER_BRASILIA' AS LeaderType UNION ALL
  SELECT 'LEADER_INDIA' AS LeaderType UNION ALL
  SELECT 'LEADER_NORTH_SEA_ALLIANCE' AS LeaderType UNION ALL
  SELECT 'LEADER_PAN_ASIA' AS LeaderType
) AS leaders
CROSS JOIN (
  SELECT 'FLAVOR_EMANCIPATION' AS FlavorType, -2 AS Flavor UNION ALL
  SELECT 'FLAVOR_HARMONY' AS FlavorType, -2 AS Flavor UNION ALL
  SELECT 'FLAVOR_PROMISED_LAND' AS FlavorType, 9 AS Flavor UNION ALL
  SELECT 'FLAVOR_PURITY' AS FlavorType, 12 AS Flavor UNION ALL
  SELECT 'FLAVOR_SUPREMACY' AS FlavorType, -2 AS Flavor UNION ALL
  SELECT 'FLAVOR_TRANSCENDENCE' AS FlavorType, -2 AS Flavor
) AS flavours;
